//SET-UP FOR EXPRESS.JS


//IMPORT FUNCTIONALITY VIA CONTROLLER METHODS


//SET GET AND POST ROUTES TO  /api/modelnames


//SET POST ROUTES TO  /api/modelnames/bulk


//SET GET ONE, PUT, AND DELETE AT /api/modelnames/:ID


//EXPORT